
name: main
on: [push, pull_request]

jobs:
  lein-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: |
            17
            21
      - uses: actions/cache@v3
        with:
          key: apt-${{ matrix.jdk }}
          path: |
            ~/.m2/repository
            /var/cache/apt/archives/*.deb
      - run: sudo -i apt-get update
      - run: sudo -i apt-get -y install leiningen
      - name: lein test (jdk 17)
        run: dev/java-env --expect-major 17 "${JAVA_HOME_17_X64}" dev/run-test --use-sudo
      - name: lein test (jdk 21)
        run: dev/java-env --expect-major 21 "${JAVA_HOME_21_X64}" dev/run-test --use-sudo
